/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin/Balance': RouteRecordInfo<'/admin/Balance', '/admin/Balance', Record<never, never>, Record<never, never>>,
    '/admin/FAQEditor': RouteRecordInfo<'/admin/FAQEditor', '/admin/FAQEditor', Record<never, never>, Record<never, never>>,
    '/admin/Orders': RouteRecordInfo<'/admin/Orders', '/admin/Orders', Record<never, never>, Record<never, never>>,
    '/admin/templates/TemplateCreate': RouteRecordInfo<'/admin/templates/TemplateCreate', '/admin/templates/TemplateCreate', Record<never, never>, Record<never, never>>,
    '/admin/templates/TemplateEdit': RouteRecordInfo<'/admin/templates/TemplateEdit', '/admin/templates/TemplateEdit', Record<never, never>, Record<never, never>>,
    '/admin/templates/TemplatesList': RouteRecordInfo<'/admin/templates/TemplatesList', '/admin/templates/TemplatesList', Record<never, never>, Record<never, never>>,
    '/client/AAMVA': RouteRecordInfo<'/client/AAMVA', '/client/AAMVA', Record<never, never>, Record<never, never>>,
    '/client/Balance': RouteRecordInfo<'/client/Balance', '/client/Balance', Record<never, never>, Record<never, never>>,
    '/client/DateAAA': RouteRecordInfo<'/client/DateAAA', '/client/DateAAA', Record<never, never>, Record<never, never>>,
    '/client/Docs': RouteRecordInfo<'/client/Docs', '/client/Docs', Record<never, never>, Record<never, never>>,
    '/client/generator/AAMVA': RouteRecordInfo<'/client/generator/AAMVA', '/client/generator/AAMVA', Record<never, never>, Record<never, never>>,
    '/client/generator/Docs': RouteRecordInfo<'/client/generator/Docs', '/client/generator/Docs', Record<never, never>, Record<never, never>>,
    '/client/generator/MRZ': RouteRecordInfo<'/client/generator/MRZ', '/client/generator/MRZ', Record<never, never>, Record<never, never>>,
    '/client/generator/PN': RouteRecordInfo<'/client/generator/PN', '/client/generator/PN', Record<never, never>, Record<never, never>>,
    '/client/MRZ': RouteRecordInfo<'/client/MRZ', '/client/MRZ', Record<never, never>, Record<never, never>>,
    '/client/Orders': RouteRecordInfo<'/client/Orders', '/client/Orders', Record<never, never>, Record<never, never>>,
    '/client/PN': RouteRecordInfo<'/client/PN', '/client/PN', Record<never, never>, Record<never, never>>,
    '/client/Subscription': RouteRecordInfo<'/client/Subscription', '/client/Subscription', Record<never, never>, Record<never, never>>,
    '/client/Support': RouteRecordInfo<'/client/Support', '/client/Support', Record<never, never>, Record<never, never>>,
    '/Index': RouteRecordInfo<'/Index', '/Index', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
  }
}
